config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :groupings, only: %i[index new create]
  get 'groupings/external_index', to: 'groupings#external_index'
  resources :groups, only: %i[index new create show]

  get 'signup' => 'users#new'
  resources :users

  delete '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/blob_validator.rb
class BlobValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, values)
    return unless values.attached?

    Array(values).each do |value|
      if options[:size_range].present?
        if options[:size_range].min > value.blob.byte_size
          record.errors.add(attribute, :min_size_error, min_size: ActiveSupport::NumberHelper.number_to_human_size(options[:size_range].min))
        elsif options[:size_range].max < value.blob.byte_size
          record.errors.add(attribute, :max_size_error, max_size: ActiveSupport::NumberHelper.number_to_human_size(options[:size_range].max))
        end
      end

      record.errors.add(attribute, :content_type) unless valid_content_type?(value.blob)
    end
  end

  private

  def valid_content_type?(blob)
    return true if options[:content_type].nil?

    case options[:content_type]
    when Regexp
      options[:content_type].match?(blob.content_type)
    when Array
      options[:content_type].include?(blob.content_type)
    when Symbol
      blob.public_send("#{options[:content_type]}?")
    else
      options[:content_type] == blob.content_type
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 100 }
  belongs_to :user
  has_many :group_hours
  has_many :groupings, through: :group_hours
  has_one_attached :icon
  validates :icon, blob: { content_type: :image }

  def self.index_group(data_params)
    includes(:user).paginate(page: data_params, per_page: 3).order('created_at DESC').with_attached_icon
  end

  def self.show_group(params_id)
    includes(:groupings, :user).find(params_id)
  end
end

app/models/group_hour.rb
class GroupHour < ApplicationRecord
  belongs_to :group
  belongs_to :grouping
end

app/models/grouping.rb
class Grouping < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_hours
  has_many :groups, through: :group_hours
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 100 }
  validates :hours, presence: true, numericality: { less_than: 10_000 }

  def self.grouping_index(params_data, current)
    includes(groups: [icon_attachment: :blob]).paginate(page: params_data, per_page: 3)
      .where('author_id=?', current.id).joins(:groups)
  end

  def self.external(params_data, current)
    includes(groups: [icon_attachment: :blob]).paginate(page: params_data, per_page: 3)
      .where('author_id=?', current.id).left_outer_joins(:groups).where('groups.id IS NULL')
  end

  scope :grouped, -> { where.not(groups: [nil]).order('created_at DESC') }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 100 }
  has_many :groupings
  has_many :groups
  has_one_attached :avatar
  validates :avatar, blob: { content_type: :image }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :set_cache_headers

  def set_cache_headers
    response.headers['Cache-Control'] = 'no-cache, no-store'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = 'Mon, 01 Jan 1990 00:00:00 GMT'
  end

  private

  def logged_in
    return if logged_in?

    flash[:error] = ['Please login to continue']
    redirect_to root_url
  end
end

app/controllers/groupings_controller.rb
class GroupingsController < ApplicationController
  before_action :logged_in

  def index
    @groupings = Grouping.grouping_index(params[:page], current_user).grouped
  end

  def external_index
    @groupings = Grouping.external(params[:page], current_user)
    render 'index'
  end

  def new
    @grouping = Grouping.new
  end

  def create
    grouping = Grouping.new(grouping_params)
    grouping.author_id = current_user.id
    if grouping.save
      group_id = params[:grouping][:group_id]
      GroupHour.create(group_id: group_id, grouping_id: grouping.id) if group_id
      flash[:success] = 'Grouped hours added'
      redirect_to groupings_path
    else
      flash[:danger] = grouping.errors.full_messages
      redirect_back(fallback_location: new_grouping_path)
    end
  end

  private

  def grouping_params
    params.require(:grouping).permit(:name, :hours)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in

  def index
    @groups = Group.index_group(params[:page])
  end

  def new
    @group = Group.new
  end

  def create
    group = Group.new(group_params)
    group.user_id = current_user.id
    if group.save
      flash[:success] = 'Group added successfully!'
      redirect_to groups_path
    else
      flash[:danger] = group.errors.full_messages
      redirect_back(fallback_location: new_group_path)
    end
  end

  def show
    @group = Group.show_group(params[:id])
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(name: params[:name])
    if user
      log_in user
      flash[:success] = 'Successfully Logged In!'
      redirect_to user
    else
      flash.now[:alert] = 'Name not found!'
      render :new
    end
  end

  def destroy
    log_out
    flash[:success] = 'Successfully Logged Out!'
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    return unless logged_in?

    redirect_to current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Signed Up successfully!'
      redirect_to @user
    else
      flash[:danger] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = current_user
    return if logged_in?

    flash[:danger] = ['Access not allowed. Please login as this user first']
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def burger_icon
    return current_user if logged_in?

    root_path
  end

  def creation_date(obj)
    obj.created_at.strftime('%d %b %Y')
  end
end

app/helpers/groupings_helper.rb
module GroupingsHelper
  def total_hours(_groupings)
    sum = 0
    @groupings.each do |grouping|
      sum += grouping.hours
    end
    sum
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_icon(group)
    if group.icon.present?
      image_tag group.icon, class: 'group-img'
    else
      image_tag 'default-group-icon.png', class: 'group-img'
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def display_avatar(user)
    if user.avatar.present?
      image_tag user.avatar, class: 'avatar rounded-circle'
    else
      image_tag 'default-avatar.png', class: 'avatar rounded-circle'
    end
  end
end

app/views/groupings/_form.html.erb
<div class="w-75 mx-auto shadow p-4 mt-5 mb-5">
  <%= form_with model: @grouping, local: true do |g| %>
    <div class= "form-group">
      <%= g.text_field :name, class: "form-control", placeholder: "Add name here.."%>
    </div>
    <div class="form-group">
      <%= g.number_field :hours, class: "form-control", placeholder: "Add hours here.."%>
    </div>
    <div class="input-group my-3">
      <div class="input-group-prepend">
          <%= g.label :group_id, class: 'input-group-text' %>
      </div>
      <%= g.collection_select(:group_id, Group.all, :id, :name, {include_blank: true}, {class: 'custom-select'}) %>
    </div>
    <div class="green-color w-75 mx-auto rounded">
    <%= g.submit "Submit Grouping", class: "btn button mx-auto d-block"%>
    </div>
  <%end%>
</div>

app/views/groupings/_grouping.html.erb
<div class="card w-75 mx-auto my-3">
    <div class="card-body d-flex justify-content-between align-items-center">
      <div>
        <%= group_icon(grouping.groups.take) if grouping.groups.any? %>
        <%= grouping.name %>
      </div>
      <strong><%= grouping.hours%>hrs</strong>
    </div>
    <div class="card-footer">
      <%= creation_date(grouping) %>
    </div>
</div>

app/views/groupings/index.html.erb
<% provide(:title, 'Grouping Hours') %>
<%= render 'layouts/header'%>
<div class="card">
    <div class="card-body d-flex justify-content-between">
        <span> Total Hours </span>
        <%= total_hours(@groupings) %>Hours
    </div
</div>
<div class="d-flex justify-content-center mt-3">
  <%= will_paginate @groupings, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>
<div class="space-for-new">
  <%= render @groupings %>
</div>
<div class="green-color py-3 fixed-bottom">
    <%= link_to "New Grouping", new_grouping_path, type: 'button',
    class: "btn outline mx-auto d-block py-3 w-75 button" %>
</div>

app/views/groupings/new.html.erb
<% provide(:title, 'New Grouping') %>
<%= render 'layouts/header'%>
<%= render 'form' %>

app/views/groups/_form.html.erb
<div class="w-75 mx-auto shadow p-4 mt-5 mb-5">
    <%= form_with model: @group, local: true do |g| %>
    <div class= "form-group">
        <%= g.text_field :name, class: "form-control", placeholder: "Add name here.."%>
    </div>
    <div class="custom-file my-3">
    <%= g.file_field :icon, class: 'custom-file-input', direct_upload: true,accept: "image/jpeg, image/gif, image/png" %>
    <%= g.label :icon, class: 'custom-file-label' %>
    </div>
    <div class="green-color py-3 fixed-bottom">
        <%= g.submit "Create Group", class: "btn outline mx-auto w-75 py-3 d-block button"%>
    </div>
    <%end%>
</div>

app/views/groups/_group.html.erb
<div class="card w-75 mx-auto my-3">
    <div class="card-body d-flex justify-content-between">
      <%= link_to group, class: "card-link" do %>
      <%= group_icon(group) %>
       <span><%= group.name %></span>
      <% end %>
    </div>
    <div class="card-footer">
     Created by <strong><%= group.user.name%></strong> on <%= creation_date(group) %>
    </div>
</div>

app/views/groups/index.html.erb
<% provide(:title, 'All Groups') %>
<%= render 'layouts/header' %>
<div class="d-flex justify-content-center mt-3">
  <%= will_paginate @groups, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>
<div class="space-for-new">
 <%= render @groups %>
</div>
<div class="green-color py-3 fixed-bottom">
    <%= link_to 'New Group', new_group_path, class: "btn outline w-75 mx-auto d-block py-3 button" %>
</div>

app/views/groups/new.html.erb
<% provide(:title, 'New Group') %>
<%= render 'layouts/header'%>
<%= render 'form' %>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<%= render 'layouts/header' %>
<div class="card">
    <div class="card-body d-flex align-items-center">
        <%= group_icon(@group) %>
        <h2 class="ml-3">Group-Name: <%= @group.name %></h2>
    </div>
    <div class="card-footer">
        Was created by <%= @group.user.name %> on <%= creation_date(@group) %>
    </div
</div>
<div class="card mt-3">
    <div class="card-body">
        <h3> Grouped Hours On This Group </h3>
    </div>
</div>
<% @group.groupings.each do |g| %>
    <div class="card w-75 mx-auto my-3">
      <div class="card-body d-flex justify-content-between">
        <span><%= g.name %></span>
        <strong><%= g.hours%>Hours</strong>
      </div>
    </div>
  <% end %>

app/views/layouts/_errors.html.erb
<%model.errors.each do |error| %>
    <div><%= error.full_message %></div>
  <%end%>
  

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%=key%> alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= value %>
     </div>
  <% end %>
  

app/views/layouts/_header.html.erb
<nav class = "navbar navbar-dark user_page py-4">
    <%= link_to burger_icon, class: "navbar-brand" do %>
        <i class="fa fa-bars fa-lg" aria-hidden="true"></i>
    <% end %>
    <div class="navbar-nav text-white font-weight-bold">
        <%= yield(:title) %>
    </div>
    <div class = "navbar-nav font-weight-bold">
        <%= link_to('Logout', logout_path, method: 'delete', class: 'nav-link') if logged_in? %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupHoursApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/flash" %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="mx-auto w-75">
  <div class="margin">
    <h1 class="home-title text-center">Grouping Hours App</h1>
  </div>
  <p class="text-center text-capitalize paragraph"> This application will helps its users to create groups of hours they spent
  working on different projects in their universities which will help them to manage 
  how they use their time </p>
  <div class="d-flex justify-content-center mx-auto user_page mb-3 rounded">
    <%= link_to 'Sign In', login_path, class: 'btn mx-auto d-block link button' %>
  </div>
  <span class="mx-auto d-flex justify-content-center"><%= 'Or'%></span>
  <div class="d-flex justify-content-center mx-auto w-50 green-color rounded">
    <%= link_to 'Signup', signup_path, class: 'btn mx-auto d-block button' %>
  </div>
</div>

app/views/users/_alert.html.erb
<div class="alert alert-secondary" role="alert">
  <%= text %>
</div>

app/views/users/_form.html.erb
<div class="w-75 mx-auto shadow p-4 mt-5 mb-5">
  <h1 class="text-center heading title"> Create A New Account </h1>
  <div>
    <%= form_with model: @user do |f| %>
      <div class= "form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control"%>
      </div>
      <div class="custom-file my-3">
        <%= f.file_field :avatar, class: 'custom-file-input', direct_upload: true, accept: "image/jpeg, image/gif, image/png" %>
        <%= f.label :avatar, class: 'custom-file-label' %>
      </div>
      <div class="d-flex justify-content-center mx-auto green-color rounded">
      <%= f.submit "Sign Up", class: "btn mx-auto d-block button"%>
      </div>
      <div class = "bottom-link mt-3 text-center">
        <%= "Already have an account?" %>
        <%= link_to 'Sign In', login_path, class: "title"%>
      </div>
    <%end%>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'SIGN UP') %>
<%= render 'layouts/header' %>
<%= render 'form' %>

app/views/users/show.html.erb
<div class = "vh-100 text-white user_page">
    <div class="py-3 text-center">
        <%= display_avatar(@user) %>
        <h1><%= @user.name %></h1>
    </div>
    <ul class="list-group my-5">
        <li class="lists-items">
            <i class="fa mr-3 fa-globe"></i>
            <%= link_to 'All My Grouped Hours', groupings_path, class: 'text-white' %>
        </li>
        <li class="lists-items">
            <i class="fa mr-3 fa-object-group"></i>
            <%= link_to 'All My External Grouped Hours', groupings_external_index_path, class: 'text-white' %>
        </li>
        <li class="lists-items">
            <i class="fa mr-3 fa-users"></i>
            <%= link_to 'All groups', groups_path, class: 'text-white' %>
        </li>
        <li class="lists-items">
            <i class="fa mr-3 fa-sign-out"></i>
            <%= link_to('Logout', logout_path, method: 'delete', class: 'text-white') if logged_in? %>
        </li>
    </ul>
</div>